Update Redis app directory
unikraft/app-redis pull request #20
Opened 2023-09-09 18:04 UTC by razvand

Rework the contents of the Redis app directory to make it more suitable for users (prime tool is KraftKit) and for developers (prime tools are Make, Kconfig, QEMU / Firecracker).

Move and output files in dedicated directories to keep the root directory clean: `kraft.yaml`, `README.md`, `Makefile`, `Makefile.uk` are the only files in the dedicated directories.

Update `README.md` according to the new structure.

Improve support for KraftKit: documentation, run scriipts, testing.

2023-09-10 15:40 UTC, StefanJum requested changes
Looks good, just a few comments.

* Do we only provide basic config files? (i.e. not the `pie-paging` etc. ones)
* Would it make sense to keep the config naming convention kraft uses (`config.appname-arch...`)?

2023-09-10 15:40 UTC, StefanJum commented on README.md
> +```
Is that required when using `kraft`?

2023-09-10 15:40 UTC, StefanJum commented on README.md
> +     defconfigs/  fs0/  kraft.yaml  Makefile  Makefile.uk.default  README.md  run/  workdir/
```suggestion
     defconfigs/  fs0/  kraft.yaml  Makefile  Makefile.uk  README.md  run/
```

2023-09-10 15:40 UTC, StefanJum commented on README.md
>    1. Get back to the application directory:
```suggestion
```
This is not needed anymore

2023-09-10 22:44 UTC, razvand commented on README.md
> +```
Yes, I get errors if I don't do that.

2023-09-10 22:45 UTC, razvand commented
> Do we only provide basic config files? (i.e. not the pie-paging etc. ones)

I will add all of them from [the `maintainer-tools` repository]().
    Would it make sense to keep the config naming convention kraft uses (config.appname-arch...)?

2023-09-11 12:15 UTC, StefanJum reviewed
> I will add all of them from [the maintainer-tools repository](https://github.com/unikraft-upb/maintainer-tools/tree/staging/workdir/copy/base/apps/redis).

Perfect

> My thought was to simplify the names as much as possible. But if more people think we should use config.appname-..., then I will update accordingly. 

Makes sense, I don't have a strong opinion here, just if maybe the configs can be used by kraft somehow, but that should not be the case since kraft should only care about the `kraft.yaml` file.

It looks all good on my side besides the one small comment.

2023-09-11 12:15 UTC, StefanJum commented on README.md
> +     defconfigs/  fs0/  kraft.yaml  Makefile  Makefile.uk  README.md [...]  run-fc-x86_64-initrd.sh*  run-qemu-aarch64-9pfs.sh*  [...]
```suggestion
     defconfigs/  fs0/  kraft.yaml  Makefile  Makefile.uk  README.md [...]  run/  [...]
```
These will be under the `run/` directory

2023-10-01 18:02 UTC, StefanJum requested changes
Either add the `setup.sh` script (and mention it in the TLDR section) or add the cloning steps back into the `TLDR` section.

2023-10-02 07:00 UTC, StefanJum approved these changes
All good.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-10-03 15:19 UTC, merged