Fix command for manually running redis
unikraft/app-redis pull request #6
Opened 2022-07-20 13:04 UTC by mariasfiraiala

Signed-off-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2022-08-01 14:11 UTC, razvand requested changes
Hi, @mariasfiraiala . What is this useful for? I was able to run the Redis Unikraft application with the initial command.

Your version of the command is required only if the Redis application is built with 9pfs support when running:

```
make menuconfig
```

But 9pfs support is not required. Maybe there should be a fix in the documentation of [`lib-redis`](https://github.com/unikraft/lib-redis/blob/staging/README.md) to point out that 9pfs support is **not** required (unlike [`lib-nginx`](https://github.com/unikraft/lib-nginx/blob/staging/README.md) - referenced there).

2022-08-01 14:19 UTC, mariasfiraiala commented
Alright then, closing this PR. I'll take a look into the documentation for `lib-redis`.

2022-08-04 15:22 UTC, razvand commented
Hi, @mariasfiraiala . Based on our discussion, this PR is indeed useful. We require a `redis.conf` configuration file to be passed to Redis, and that needs to be done via a filesystem (such as `9pfs`).

Please update this commit with the `fs0/redis.conf` file.

This `redis.conf` file worked for me, maybe you can simplify it:

```
bind 172.44.0.2
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
```

2022-08-04 15:25 UTC, razvand commented
Also add instructions on adding `9pfs` support with the proper tag (`rootfs` in the command above), similar to the [`lib-nginx` documentation](https://github.com/unikraft/lib-nginx#root-filesystem). You could also add this to the [`lib-redis` repository](https://github.com/unikraft/lib-redis) for consistency.

I think consistency is important, so I would aim to make `Redis` and `Nginx` as close to each other as possible, documentation-wise.

2022-11-09 14:34 UTC, StefanJum reviewed
Only one comment, looks good besides that.

2022-11-09 14:34 UTC, StefanJum commented on README.md
> +```
This will al be done bt #10, there is no need to have it here.

2022-11-09 15:01 UTC, mariasfiraiala commented
> Only one comment, looks good besides that.

Thank you @StefanJum . Removed it.

2022-11-09 16:05 UTC, StefanJum requested changes
Few more comments.

2022-11-09 16:05 UTC, StefanJum commented on README.md
> +                        -device virtio-9p-pci,fsdev=myid,mount_tag=rootfs,disable-modern=on,disable-legacy=off \
```suggestion
                        -device virtio-9p-pci,fsdev=myid,mount_tag=fs0,disable-modern=on,disable-legacy=off \
```
If #10 is merged, `kraft` will use the default `fs0` mount tag.

2022-11-09 16:05 UTC, StefanJum commented on README.md
> +Be aware of the fact that you'll have to choose a file system: for instance, from the `vfscore` library, choose the `Default root filesystem` to be `9pfs`.
We should also specify that the mount tag must be `fs0` if the users will want to use `kraft` or `qemu-guest`.

2022-11-09 16:21 UTC, razvand commented on README.md
> +Be aware of the fact that you'll have to choose a file system: for instance, from the `vfscore` library, choose the `Default root filesystem` to be `9pfs`.
Agree with @StefanJum 

@mariasfiraiala , I may fucked things up as I did a force push with some updates.

Please use the new updated branch, see @StefanJum 's comments, mark conversations solved by clicking `Resolve conversation` (once they are solved) and re-request his review.

2022-11-09 18:14 UTC, StefanJum requested changes
One more little comment.

2022-11-09 18:14 UTC, StefanJum commented on README.md
> +If you are going to use the `qemu` or kraft, wrapper to launch the app, you need to name the `Default root device` `fs0` (`Library Configuration` -> `vfscore` -> `Default root device`). This is due t
```suggestion
If you are going to use the `qemu-guest` script or `kraft` to launch the app, you need to name the `Default root device` `fs0` (`Library Configuration` -> `vfscore` -> `Default root device`).
This is due to how the `qemu-guest` script and krat automatically tag the FS devices attached to `qemu`.
```

Please use one line per sentence and one sentence per line.

2022-11-09 18:31 UTC, StefanJum commented on README.md
> +This is due to how the `qemu-guest` script and krat automatically tag the FS devices attached to `qemu`.
```suggestion
This is due to how the `qemu-guest` script and kraft automatically tag the FS devices attached to `qemu`.
```

2022-11-09 18:34 UTC, StefanJum commented on README.md
> +If you are going to use the `qemu-guest` script or `kraft`, wrapper to launch the app, you need to name the `Default root device` `fs0` (`Library Configuration` -> `vfscore` -> `Default root device`)
```suggestion
If you are going to use the `qemu-guest` script or `kraft` to launch the app, you need to name the `Default root device` `fs0` (`Library Configuration` -> `vfscore` -> `Default root device`).
```

2022-11-09 18:38 UTC, StefanJum approved these changes
All good, thank you @mariasfiraiala.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-11-10 03:39 UTC, razvand commented
@mariasfiraiala , please mark solved items with `Resolve conversation` and re-request reviews from reviewers (@StefanJum in this case).

2022-11-15 08:38 UTC, razvand approved these changes
This works. Thanks, @mariasfiraiala 

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2022-11-28 14:52 UTC, closed without merging